# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
