# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 02:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170107_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('card_picture', models.FileField(upload_to=user.models.directory_path)),
                ('image', models.FileField(blank=True, null=True, upload_to=user.models.card_image_directory_path)),
                ('audio', models.FileField(blank=True, null=True, upload_to=user.models.card_audio_directory_path)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('downloads', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, default='free', max_length=10, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('character', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('id_card', models.ForeignKey(db_column='id_card', on_delete=django.db.models.deletion.CASCADE, to='user.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(upload_to=user.models.directory_path)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('id_card', models.ForeignKey(db_column='id_card', on_delete=django.db.models.deletion.CASCADE, to='user.Card')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='id_theme',
            field=models.ForeignKey(db_column='id_theme', on_delete=django.db.models.deletion.CASCADE, to='user.Theme'),
        ),
        migrations.AddField(
            model_name='card',
            name='id_category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='id_theme',
            field=models.ForeignKey(db_column='id_theme', on_delete=django.db.models.deletion.CASCADE, to='user.Theme'),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together=set([('id_user', 'id_card')]),
        ),
    ]
